### ISSUE TITLE
Find a better way to add nix to path

### ISSUE THREAD

**Issue by staticdev** [staticdev/linux-workstation-playbook#391]
`ableton.nix` currently does not do that and just adding to `packages.yml`:

```yaml
- name: Add Nix to PATH
  ansible.builtin.set_fact:
    ansible_env: "{{ ansible_env | combine({'PATH': ansible_env.HOME + '/.nix-profile/bin:' + ansible_env.PATH}) }}"
```

Did not work. Currently all commands have appended:

```yaml
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}
```

Find a better solution and remove it.
